//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieUrls_64130299
    {
        public string MovieUrlId { get; set; }
        public string MovieId { get; set; }
        public string Url { get; set; }
    
        public virtual Movie_64130299 Movie_64130299 { get; set; }
    }
}
