//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSubscription_64130299
    {
        public string SubscriptionId { get; set; }
        public string UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string AccessLevel { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int PlanId { get; set; }
        public string PaymentMethod { get; set; }
        public decimal AmountPaid { get; set; }
    
        public virtual User_64130299 User_64130299 { get; set; }
        public virtual SubscriptionPlans_64130299 SubscriptionPlans_64130299 { get; set; }
    }
}
