//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Movie_64130299
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie_64130299()
        {
            this.Favorite_64130299 = new HashSet<Favorite_64130299>();
            this.MovieUrls_64130299 = new HashSet<MovieUrls_64130299>();
            this.Rating_64130299 = new HashSet<Rating_64130299>();
        }

        [DisplayName("Mã Phim")]
        public string MovieId { get; set; }

        [DisplayName("Tiêu Đề")]
        public string Title { get; set; }

        [DisplayName("Mô Tả")]
        public string Description { get; set; }

        [DisplayName("Định Dạng")]
        public Nullable<bool> GenreId { get; set; }

        [DisplayName("Thể Loại")]
        public string GenreName { get; set; }

        [DisplayName("Tên Đạo Diễn")]
        public string DirectorName { get; set; }

        [DisplayName("Tên Diễn Viên")]
        public string ActorName { get; set; }

        [DisplayName("Quốc Gia")]
        public string Country { get; set; }

        [DisplayName("Ngày Phát Hành")]
        public Nullable<System.DateTime> ReleaseDate { get; set; }

        [DisplayName("URL Poster")]
        public string PosterUrl { get; set; }

        [DisplayName("URL Trailer")]
        public string TrailerUrl { get; set; }

        [DisplayName("Ngày Tạo")]
        public Nullable<System.DateTime> CreatedAt { get; set; }

        [DisplayName("Ngày Cập Nhật")]
        public Nullable<System.DateTime> UpdatedAt { get; set; }

        [DisplayName("Cấp Độ Truy Cập")]
        public string AccessLevel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite_64130299> Favorite_64130299 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieUrls_64130299> MovieUrls_64130299 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating_64130299> Rating_64130299 { get; set; }
    }
}
